### ISSUE TITLE
Campaigner consumer changes to reflect the templates rewrite

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#994]
Draft design of the flow:

![campaigner](https://user-images.githubusercontent.com/35736870/104511562-346b7600-55ed-11eb-8f71-169372d11360.png)

Update the image if there are any changes, and add retries on this [link](https://excalidraw.com/#json=5093034890887168,6VoVfhhTZinc-nEt6I7bbw)

**Comment by Dzalevski** [comment]
7h.

**Comment by Dzalevski** [comment]
3h

**Comment by gudgl** [comment]
![redesign](https://user-images.githubusercontent.com/35736870/105768133-38d44f00-5f5c-11eb-8c8b-ea9ab34fee81.png)

or click the link to edit -> https://excalidraw.com/#json=6440907431739392,s7Wj-mkBC2M1ZcTwZ2kA9g

On this image all 3 parts of the flow are represented in short. 

First pay attention to the methods in for loop they are called for each subscriber and if there is error there we can not retry the message. So if there is an error for a specific subscriber we can add record in `sender_logs` with all info we need even if we want to retry "the publishing" just for one subscriber.

In the sender we think its best if we insert record in sends for each subscriber at the beginning of the sender for idempotency and at the end update the status to sent or failed (with specific reason).

Also we taught about moving `PrepareSubscriberEmailData` to the sender so we will have a clear single responsibility.

This is just a non detail proposal, its better if we all sit down together and do the details because 3 heads are more than 2 :sunglasses:

**Comment by gudgl** [comment]
2h

**Comment by Dzalevski** [comment]
@gudgl We discussed about PrepareSubscriberEmailData that can not be in sender because we need template data to be fetched only once not for every subscriber.
