### ISSUE TITLE
Send campaign - validate template with default template data

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#996]
![POST_start_campaign](https://user-images.githubusercontent.com/35736870/104828709-8bcb4980-586c-11eb-9e49-ba2f8702ebe8.png)

Update the image if there are any changes, and add retries on this [link](https://excalidraw.com/#json=5760509450125312,MwHnUvwWUjWiaZfWAtar0w)

**Comment by gudgl** [comment]
As I remember this validation means if default template data have all the fields needed for the template.
This can confuse users maybe we can improve the whole flow about starting campaign. With something like this demo (here)[http://mustache.github.io/#demo]. Some other thing is checking all the tags one by one because Render don't catch missing fields.

2h

**Comment by gudgl** [comment]
Don't forget to check the diagram

**Comment by gudgl** [comment]
3h
